[dev]
  # Le dice a Netlify que la aplicación web (index.html) está en la carpeta actual (.)
  publish = "."
  # Fuerza la carga en el puerto que usa para los archivos estáticos
  targetPort = 3999
  # Esto le dice a Netlify que escuche en todas las interfaces de red (soluciona bloqueos en Windows)
  address = "0.0.0.0"
